package org.my.mybatis.service.dao.mybatis.model;

public class Idea {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.syskey
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    private String syskey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.ideaType
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    private String ideatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.ideaContents
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    private String ideacontents;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.ideaWho
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    private String ideawho;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.ideaWhere
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    private String ideawhere;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.ideaHappened
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    private String ideahappened;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column idea.ideaTimeAndDate
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    private String ideatimeanddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.syskey
     *
     * @return the value of idea.syskey
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public String getSyskey() {
        return syskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.syskey
     *
     * @param syskey the value for idea.syskey
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public void setSyskey(String syskey) {
        this.syskey = syskey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.ideaType
     *
     * @return the value of idea.ideaType
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public String getIdeatype() {
        return ideatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.ideaType
     *
     * @param ideatype the value for idea.ideaType
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public void setIdeatype(String ideatype) {
        this.ideatype = ideatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.ideaContents
     *
     * @return the value of idea.ideaContents
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public String getIdeacontents() {
        return ideacontents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.ideaContents
     *
     * @param ideacontents the value for idea.ideaContents
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public void setIdeacontents(String ideacontents) {
        this.ideacontents = ideacontents;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.ideaWho
     *
     * @return the value of idea.ideaWho
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public String getIdeawho() {
        return ideawho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.ideaWho
     *
     * @param ideawho the value for idea.ideaWho
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public void setIdeawho(String ideawho) {
        this.ideawho = ideawho;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.ideaWhere
     *
     * @return the value of idea.ideaWhere
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public String getIdeawhere() {
        return ideawhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.ideaWhere
     *
     * @param ideawhere the value for idea.ideaWhere
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public void setIdeawhere(String ideawhere) {
        this.ideawhere = ideawhere;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.ideaHappened
     *
     * @return the value of idea.ideaHappened
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public String getIdeahappened() {
        return ideahappened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.ideaHappened
     *
     * @param ideahappened the value for idea.ideaHappened
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public void setIdeahappened(String ideahappened) {
        this.ideahappened = ideahappened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column idea.ideaTimeAndDate
     *
     * @return the value of idea.ideaTimeAndDate
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public String getIdeatimeanddate() {
        return ideatimeanddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column idea.ideaTimeAndDate
     *
     * @param ideatimeanddate the value for idea.ideaTimeAndDate
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    public void setIdeatimeanddate(String ideatimeanddate) {
        this.ideatimeanddate = ideatimeanddate;
    }
}