package org.my.mybatis.service.dao.mybatis.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.my.mybatis.service.dao.mybatis.model.Idea;
import org.my.mybatis.service.dao.mybatis.model.IdeaExample;

public interface IdeaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    long countByExample(IdeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int deleteByExample(IdeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int deleteByPrimaryKey(String syskey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int insert(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int insertSelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    List<Idea> selectByExample(IdeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    Idea selectByPrimaryKey(String syskey);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int updateByExampleSelective(@Param("record") Idea record, @Param("example") IdeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int updateByExample(@Param("record") Idea record, @Param("example") IdeaExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int updateByPrimaryKeySelective(Idea record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table idea
     *
     * @mbg.generated Mon Jun 21 17:14:14 CST 2021
     */
    int updateByPrimaryKey(Idea record);
}